### PR TITLE
digitalservicebund/icons v2

### PR DESCRIPTION
**Pull request by pgurusinga**
# Problem
Since we are ESM-project and `@digitalservicebund/icons` is a CJS-type lib, we would need Vite's `vite-plugin-cjs-interop` to make the library work in our application

# Proposed Changes 
- Apply icons v2 https://github.com/digitalservicebund/icons/blob/main/CHANGELOG.md
- Remove Vite Interop helper
- Adapt `tsconfig` to resolve path

### CODE REVIEW

**Comment by aaschlote** [comment]
Can you check now if we update the dependency `tsx` to the version `^4.15.1`, the generation of CMS file doesn't it fail?

**Comment by pgurusinga** [comment]
@aaschlote yes, i checked last week and it works without this change ;) , but it won't be part of this PR

**Comment by aaschlote** [comment]
> @aaschlote yes, i checked last week and it works without this change ;) , but it won't be part of this PR

Wasn't it failing before due the update of the dependency (tsx)? 🤔

**Review by aaschlote — APPROVED** [review]

**Review by eliflores — APPROVED** [review]
🚀

**Review by chohner — APPROVED** [review]
nice!

**Pull request merged**
