### PR TITLE
Remove link text logic

### PR DESCRIPTION
**Pull request by aaschlote**

### CODE REVIEW

**Review by eliflores — APPROVED** [review]
LGTM 👍

**Review by pgurusinga — APPROVED** [review]
I would also ask Rast to have a look at this PR

**Review by frederike-ramin — CHANGES_REQUESTED** [review]
Very glad you asked for a review, because, no, that is not quite what I meant with deleting the "delete data" logic. I meant deleting the whole logic inside `app/services/flow/server/lastStep.ts` concerning `dataDeletionKey`. Could you remove that as well as this is the only place this is ever used?

**Comment by aaschlote** [comment]
> dataDeletionKey

**Comment by aaschlote** [comment]
> Very glad you asked for a review, because, no, that is not quite what I meant with deleting the "delete data" logic. I meant deleting the whole logic inside `app/services/flow/server/lastStep.ts` concerning `dataDeletionKey`. Could you remove that as well as this is the only place this is ever used?

Thanks, yes this is the only place in the source code where we have this `dataDeletionKey`, but I found out this URL in strapi where it calls the `deleteData` as query parameter. The others knows this functionality won't work anymore? I can remove it from Strapi.

image

**Comment by aaschlote** [comment]
> That's pretty new and it seems to be on one of your pages? `/fluggastrechte/vorabcheck/ersatzflug-starten-eine-landen-zwei-abbruch` so maybe check with your designers again?

Sure, I'll talk with them about it before to merge this PR

**Review by frederike-ramin — APPROVED** [review]
Nice, that's what I meant.

**Pull request merged**
